## Citi Bike Prediction Project — Data Acquisition and Preprocessing

This notebook combines Citi Bike station data, historical station snapshots, and MTA station data into a cleaned dataset for modeling. The target identifies stations that currently have adequate dock availability but fall to 10% or less within the next 30 minutes.

#### Load libraries

Import the libraries used for data loading, cleaning, geospatial matching, and preprocessing.

The workflow in this notebook combines:
- Citi Bike station metadata from the GBFS API.
- Citi Bike station status snapshots collected over time.
- MTA subway station data for transit-access feature engineering.

In [1]:
# Core analysis libraries
import pandas as pd
import numpy as np
import datetime
import time

# File path locations
from pathlib import Path

# Load data pull libraries
import requests
import json

# Visualization libraries
import matplotlib.pyplot as plt
import seaborn as sns

# Improve plot styling
sns.set()

# Show all columns
pd.set_option('display.max_columns', None)

#### Load data directories

Define the project folders used to load raw data and save cleaned outputs.

In [2]:
# File paths
PROJECT_ROOT = Path.cwd().resolve().parent
CLEAN_DATA_DIR = PROJECT_ROOT / "data/clean_data"
RAW_DATA_DIR = PROJECT_ROOT / "data/raw_data"
MODELS_DIR = PROJECT_ROOT / "models"
SRC_DIR = PROJECT_ROOT / "src"
DEPLOYMENT_DIR = PROJECT_ROOT / "deployment"

#### Import and inspect `station_information`

Load Citi Bike station metadata and check its structure, missing values, and station coverage before cleaning. These fields will later be used to:
- identify valid NYC stations
- support geospatial feature engineering
- provide station-level context for the prediction dataset

In [3]:
# Load 'station_information' data from API
station_info_url = "https://gbfs.lyft.com/gbfs/1.1/bkn/en/station_information.json"
response = requests.get(station_info_url, timeout=10)
response.raise_for_status()

payload = response.json()
rows = payload["data"]["stations"]

# Import into a dataframe
station_info = pd.DataFrame(rows)

# Save as parquet file
station_info.to_parquet(RAW_DATA_DIR / "01_station_info.parquet")

In [4]:
# Load data saved as a parquet file
station_info = pd.read_parquet(
    RAW_DATA_DIR / "01_station_info.parquet",
    columns = ["station_id","name","lat","lon","capacity", "region_id"]
)

In [5]:
# Show first five records of data
station_info.head(5)

,station_id,name,lat,lon,capacity,region_id
0,dd482585-3028-453f-a98d-55019db9b26c,2 Ave & 36 St,40.657089,-74.008702,43,71
1,2250953816197165238,New Lots Ave & Van Sinderen Ave,40.659230,-73.899150,0,71
2,2250954679485591748,Van Siclen Ave & Linden Blvd,40.660850,-73.886080,0,71
3,2250952758815752682,Dumont Ave & Barbey St,40.667590,-73.886090,0,71
4,90b141b9-c39f-4a26-a32d-08c7d1474d52,Lafayette Ave & Hunts Point Ave,40.816567,-73.888161,22,71

In [6]:
# Number of rows and columns
station_info.shape

(2508, 6)

In [7]:
# Data types along with count of missing
station_info_types = pd.DataFrame()
station_info_types["Data Type"] = station_info.dtypes
station_info_types["Count of Nulls"] = station_info.isna().sum()
station_info_types

           Data Type  Count of Nulls
station_id    object               0
name          object               0
lat          float64               0
lon          float64               0
capacity       int64               0
region_id     object              13

In [8]:
# unique station_ids
station_info["station_id"].nunique()

2508

#### Filter and standardize `station_information`

Keep valid NYC stations with positive capacity and rename the location fields for clarity. This leaves 2,347 stations for the remaining preprocessing steps.

Key cleanup steps include:
- restricting the data to NYC stations only
- removing stations with invalid or zero capacity
- renaming location fields for clarity and consistency

In [9]:
# Keep only 'region_id' = 71 as this is NYC
station_info = station_info[station_info["region_id"] == "71"].copy()
station_info.shape

(2388, 6)

In [10]:
# Keep only stations where capacity is > 0
station_info = station_info[station_info["capacity"] > 0].copy()
station_info.shape

(2347, 6)

In [11]:
# Rename "lat" and "lon" columns
station_info = station_info.rename(columns={
    "name":"citi_bike_station_name",
    "lat":"citi_bike_lat",
    "lon":"citi_bike_lon"
}).copy()

station_info.columns

Index(['station_id', 'citi_bike_station_name', 'citi_bike_lat',
       'citi_bike_lon', 'capacity', 'region_id'],
      dtype='object')

#### MTA station data

Load MTA subway station locations and keep the fields needed to measure transit proximity for each Citi Bike station. The preparation here focuses on:
- standardizing column names
- reducing the data to the fields needed for spatial matching
- preparing the data for nearest-station calculations

In [12]:
mta = pd.read_parquet(RAW_DATA_DIR / "00_mta_subway_stations.parquet")

In [13]:
mta.head()

,GTFS Stop ID,Station ID,Complex ID,Division,Line,Stop Name,Borough,CBD,Daytime Routes,Structure,GTFS Latitude,GTFS Longitude,North Direction Label,South Direction Label,ADA,ADA Northbound,ADA Southbound,ADA Notes,Georeference
0,127,317,611,IRT,Broadway - 7Av,Times Sq-42 St,M,True,1 2 3,Subway,40.755290,-73.987495,Uptown,Downtown,1,1,1,None,POINT (-73.987495 40.75529)
1,S17,515,515,SIR,Staten Island,Annadale,SI,False,SIR,Open Cut,40.540460,-74.178217,Ferry,South Shore,0,0,0,None,POINT (-74.178217 40.54046)
2,S01,139,627,BMT,Franklin Shuttle,Franklin Av,Bk,False,S,Elevated,40.680596,-73.955827,Last Stop,Prospect Park,1,1,1,None,POINT (-73.955827 40.680596)
3,254,349,349,IRT,Eastern Pky,Junius St,Bk,False,3,Elevated,40.663515,-73.902447,Manhattan,New Lots,0,0,0,None,POINT (-73.902447 40.663515)
4,M01,108,108,BMT,Myrtle Av,Middle Village-Metropolitan Av,Q,False,M,Elevated,40.711396,-73.889601,Inbound,Last Stop,1,1,1,None,POINT (-73.889601 40.711396)

In [14]:
# Make column names consistent format
mta.columns = (
    mta.columns.str.strip()
             .str.lower()
             .str.replace(" ", "_")
             .str.replace("-", "_")
)

mta.columns

Index(['gtfs_stop_id', 'station_id', 'complex_id', 'division', 'line',
       'stop_name', 'borough', 'cbd', 'daytime_routes', 'structure',
       'gtfs_latitude', 'gtfs_longitude', 'north_direction_label',
       'south_direction_label', 'ada', 'ada_northbound', 'ada_southbound',
       'ada_notes', 'georeference'],
      dtype='object')

In [15]:
# Reduce to only needed columns
mta_reduced = mta[["stop_name", 
                   "gtfs_latitude", 
                   "gtfs_longitude"
                  ]].copy()

mta_reduced.columns

Index(['stop_name', 'gtfs_latitude', 'gtfs_longitude'], dtype='object')

#### Import and inspect `station_status`

Combine the historical Citi Bike station snapshots that capture available bikes, available docks, and reporting times. These observations provide the time series used to build the prediction target. `station status` is dynamic and captures operational conditions such as:
- available bikes
- available docks
- reporting timestamps

In [16]:
# Import all JSON files
json_files = sorted((RAW_DATA_DIR / "snapshots").rglob("*.json"))

snapshots_dfs = []

for file_path in json_files:
    with open(file_path, "r", encoding="utf-8") as f:
        snapshot = json.load(f)

    df = pd.DataFrame(snapshot["station_status"]["data"]["stations"])
    df["snapshot_time_utc"] = snapshot["snapshot_time_utc"]
    snapshots_dfs.append(df)

In [17]:
# Compile all JSON files
station_status_full_df = pd.concat(snapshots_dfs, ignore_index=True)

In [18]:
# Reduce to just five columns
station_status = station_status_full_df[[
    "station_id", 
    "num_bikes_available", 
    "num_docks_available", 
    "snapshot_time_utc", 
    "last_reported"
]].copy()

In [19]:
# Number of rows and columns
station_status.shape

(1793173, 5)

In [20]:
# View first five rows
station_status.head(5)

,station_id,num_bikes_available,num_docks_available,snapshot_time_utc,last_reported
0,2235290968119410012,0,0,2026-07-30T11:00:42.909905+00:00,86400
1,2235289947989388178,0,0,2026-07-30T11:00:42.909905+00:00,86400
2,2235288981858690806,0,0,2026-07-30T11:00:42.909905+00:00,86400
3,66dd1f44-0aca-11e7-82f6-3863bb44ef7c,0,0,2026-07-30T11:00:42.909905+00:00,1782236251
4,90b141b9-c39f-4a26-a32d-08c7d1474d52,0,0,2026-07-30T11:00:42.909905+00:00,1781794028

In [21]:
# Data types along with count of missing
station_status_dtypes = pd.DataFrame()
station_status_dtypes["Data Type"] = station_status.dtypes
station_status_dtypes["Count of Nulls"] = station_status.isna().sum()
station_status_dtypes

                    Data Type  Count of Nulls
station_id             object               0
num_bikes_available     int64               0
num_docks_available     int64               0
snapshot_time_utc      object               0
last_reported           int64               0

#### Clean timestamps and derive time features

Standardize the timestamp fields, remove invalid reporting times, and create hour, weekday, and weekend features for later analysis. The main goals here are to:
- convert raw reporting fields into usable datetime values
- remove rows with invalid or missing timestamps
- derive basic time features such as hour of day and weekday

In [22]:
# Make 'last_reported' numeric field
station_status["last_reported"] = pd.to_numeric(station_status["last_reported"], errors="coerce")

# Make datetime anything above the year '2001'
threshold = 1000000000
station_status["timestamp"] = pd.to_datetime(
    station_status["last_reported"].where(station_status["last_reported"] > threshold), 
    errors="coerce",
    unit="s"
)

station_status.head()

,station_id,num_bikes_available,num_docks_available,snapshot_time_utc,last_reported,timestamp
0,2235290968119410012,0,0,2026-07-30T11:00:42.909905+00:00,86400,NaT
1,2235289947989388178,0,0,2026-07-30T11:00:42.909905+00:00,86400,NaT
2,2235288981858690806,0,0,2026-07-30T11:00:42.909905+00:00,86400,NaT
3,66dd1f44-0aca-11e7-82f6-3863bb44ef7c,0,0,2026-07-30T11:00:42.909905+00:00,1782236251,2026-06-23 17:37:31
4,90b141b9-c39f-4a26-a32d-08c7d1474d52,0,0,2026-07-30T11:00:42.909905+00:00,1781794028,2026-06-18 14:47:08

In [23]:
# Make 'snapshot_time_utc' standard datetime
station_status["snapshot_time"] = (
    pd.to_datetime(station_status["snapshot_time_utc"], utc=True).dt.floor("s").dt.tz_localize(None)
)

station_status.head()

,station_id,num_bikes_available,num_docks_available,snapshot_time_utc,last_reported,timestamp,snapshot_time
0,2235290968119410012,0,0,2026-07-30T11:00:42.909905+00:00,86400,NaT,2026-07-30 11:00:42
1,2235289947989388178,0,0,2026-07-30T11:00:42.909905+00:00,86400,NaT,2026-07-30 11:00:42
2,2235288981858690806,0,0,2026-07-30T11:00:42.909905+00:00,86400,NaT,2026-07-30 11:00:42
3,66dd1f44-0aca-11e7-82f6-3863bb44ef7c,0,0,2026-07-30T11:00:42.909905+00:00,1782236251,2026-06-23 17:37:31,2026-07-30 11:00:42
4,90b141b9-c39f-4a26-a32d-08c7d1474d52,0,0,2026-07-30T11:00:42.909905+00:00,1781794028,2026-06-18 14:47:08,2026-07-30 11:00:42

In [24]:
# Check number of values where "timestamp" is 'NaT'
station_status[station_status["timestamp"].isna()].shape

(57137, 7)

In [25]:
# Drop rows where timestamp is unavailable
station_status = station_status.dropna(subset=["timestamp"]).copy()
station_status.shape

(1736036, 7)

In [26]:
# Check number of values where "snapshot_time" is 'NaT'
station_status[station_status["snapshot_time"].isna()].shape

(0, 7)

In [27]:
# Drop rows where "snapshot_time" is unavailable
station_status = station_status.dropna(subset=["snapshot_time"]).copy()
station_status.shape

(1736036, 7)

In [28]:
# Create hour, weekday columns
station_status["snapshot_hr"] = station_status["snapshot_time"].dt.hour
station_status["snapshot_weekday"] = station_status["snapshot_time"].dt.dayofweek

station_status[~station_status["timestamp"].isna()].head(5)

,station_id,num_bikes_available,num_docks_available,snapshot_time_utc,last_reported,timestamp,snapshot_time,snapshot_hr,snapshot_weekday
3,66dd1f44-0aca-11e7-82f6-3863bb44ef7c,0,0,2026-07-30T11:00:42.909905+00:00,1782236251,2026-06-23 17:37:31,2026-07-30 11:00:42,11,3
4,90b141b9-c39f-4a26-a32d-08c7d1474d52,0,0,2026-07-30T11:00:42.909905+00:00,1781794028,2026-06-18 14:47:08,2026-07-30 11:00:42,11,3
7,1786700154621508184,0,0,2026-07-30T11:00:42.909905+00:00,1782217425,2026-06-23 12:23:45,2026-07-30 11:00:42,11,3
15,0de1f95f-8b1b-4e5e-9eff-73c63265b0ab,0,0,2026-07-30T11:00:42.909905+00:00,1783954261,2026-07-13 14:51:01,2026-07-30 11:00:42,11,3
16,b713367c-3572-4225-b74a-9319ab537838,0,0,2026-07-30T11:00:42.909905+00:00,1784559014,2026-07-20 14:50:14,2026-07-30 11:00:42,11,3

In [29]:
# Add a column for weekend indicator
weekend_function = lambda x : 1 if (x == 5 or  x == 6) else 0

station_status["is_weekend"] = station_status["snapshot_weekday"].apply(weekend_function)

station_status.head()

,station_id,num_bikes_available,num_docks_available,snapshot_time_utc,last_reported,timestamp,snapshot_time,snapshot_hr,snapshot_weekday,is_weekend
3,66dd1f44-0aca-11e7-82f6-3863bb44ef7c,0,0,2026-07-30T11:00:42.909905+00:00,1782236251,2026-06-23 17:37:31,2026-07-30 11:00:42,11,3,0
4,90b141b9-c39f-4a26-a32d-08c7d1474d52,0,0,2026-07-30T11:00:42.909905+00:00,1781794028,2026-06-18 14:47:08,2026-07-30 11:00:42,11,3,0
7,1786700154621508184,0,0,2026-07-30T11:00:42.909905+00:00,1782217425,2026-06-23 12:23:45,2026-07-30 11:00:42,11,3,0
15,0de1f95f-8b1b-4e5e-9eff-73c63265b0ab,0,0,2026-07-30T11:00:42.909905+00:00,1783954261,2026-07-13 14:51:01,2026-07-30 11:00:42,11,3,0
16,b713367c-3572-4225-b74a-9319ab537838,0,0,2026-07-30T11:00:42.909905+00:00,1784559014,2026-07-20 14:50:14,2026-07-30 11:00:42,11,3,0

In [30]:
# Drop "snapshot_time_utc" and "last_reported"
station_status = station_status.drop(columns=["snapshot_time_utc", "last_reported"], axis=1)
station_status.columns

Index(['station_id', 'num_bikes_available', 'num_docks_available', 'timestamp',
       'snapshot_time', 'snapshot_hr', 'snapshot_weekday', 'is_weekend'],
      dtype='object')

#### Find nearest MTA station to each Citi Bike station

Use nearest-neighbor matching to identify the closest subway station and calculate its distance from each Citi Bike station.

Transit access may influence biking demand, especially around commuting corridors, so this step adds an interpretable location-based feature:
- nearest subway station
- distance to nearest subway station in meters

In [31]:
# Import library
from sklearn.neighbors import BallTree

In [32]:
# Create Citi Bike radians
citi_bike_radians = np.radians(station_info[["citi_bike_lat", "citi_bike_lon"]])

In [33]:
# Create MTA subway station radians
mta_radians = np.radians(mta_reduced[["gtfs_latitude","gtfs_longitude"]])

In [34]:
# Build BallTree
mta_tree = BallTree(mta_radians, metric="haversine")

In [35]:
# Query for nearest station
mta_distances, mta_indices = mta_tree.query(citi_bike_radians, k=1)

In [36]:
# Earth radius in meters
earth_radius = 6371000

# Convert distances from radians to meters
mta_distance_m = mta_distances * earth_radius

In [37]:
# Add results back to dataframe
station_info["nearest_mta_station"] = mta_reduced["stop_name"].iloc[mta_indices.flatten()].values
station_info["meters_to_nearest_mta_station"] = mta_distance_m.flatten()

station_info.head()

,station_id,citi_bike_station_name,citi_bike_lat,citi_bike_lon,capacity,region_id,nearest_mta_station,meters_to_nearest_mta_station
0,dd482585-3028-453f-a98d-55019db9b26c,2 Ave & 36 St,40.657089,-74.008702,43,71,36 St,485.504501
4,90b141b9-c39f-4a26-a32d-08c7d1474d52,Lafayette Ave & Hunts Point Ave,40.816567,-73.888161,22,71,Hunts Point Av,526.964342
5,1795146692060860976,Longfellow Ave & Aldus St,40.823194,-73.887629,24,71,Hunts Point Av,350.379805
6,06439006-11b6-44f0-8545-c9d39035f32a,Vesey St & Church St,40.712220,-74.010472,78,71,World Trade Center,70.844613
9,b713367c-3572-4225-b74a-9319ab537838,Sedgwick Ave & Hall of Fame Terrace,40.859532,-73.913303,19,71,207 St,731.859863

#### Merge `station_information` and `station_status`

Merge station metadata with the historical status snapshots so each observation contains current availability, station characteristics, and transit proximity.

Post-merge checks are included to identify unmatched stations and remove records that are incomplete or not suitable for modeling.

In [38]:
station_data_merged = station_status.merge(
    station_info,
    on="station_id",
    how="left",
    suffixes=(None, None)
).sort_values(by=["station_id", "snapshot_time"], ascending=[True, True])

station_data_merged.head(5)

,station_id,num_bikes_available,num_docks_available,timestamp,snapshot_time,snapshot_hr,snapshot_weekday,is_weekend,citi_bike_station_name,citi_bike_lat,citi_bike_lon,capacity,region_id,nearest_mta_station,meters_to_nearest_mta_station
2010,00284700-9d22-42ce-8485-113fed9879c1,11,6,2026-07-30 10:58:57,2026-07-30 11:00:42,11,3,0,28 Ave & 44 St,40.764089,-73.910651,19.0,71,46 St,893.80959
4529,00284700-9d22-42ce-8485-113fed9879c1,11,6,2026-07-30 11:29:19,2026-07-30 11:30:42,11,3,0,28 Ave & 44 St,40.764089,-73.910651,19.0,71,46 St,893.80959
7006,00284700-9d22-42ce-8485-113fed9879c1,10,8,2026-07-30 11:58:40,2026-07-30 12:00:43,12,3,0,28 Ave & 44 St,40.764089,-73.910651,19.0,71,46 St,893.80959
9077,00284700-9d22-42ce-8485-113fed9879c1,2,15,2026-07-30 12:27:50,2026-07-30 12:30:42,12,3,0,28 Ave & 44 St,40.764089,-73.910651,19.0,71,46 St,893.80959
11468,00284700-9d22-42ce-8485-113fed9879c1,3,14,2026-07-30 12:58:10,2026-07-30 13:00:43,13,3,0,28 Ave & 44 St,40.764089,-73.910651,19.0,71,46 St,893.80959

In [39]:
# Check number of missing values on merged dataset
station_data_merged.isna().sum()

station_id                           0
num_bikes_available                  0
num_docks_available                  0
timestamp                            0
snapshot_time                        0
snapshot_hr                          0
snapshot_weekday                     0
is_weekend                           0
citi_bike_station_name           85217
citi_bike_lat                    85217
citi_bike_lon                    85217
capacity                         85217
region_id                        85217
nearest_mta_station              85217
meters_to_nearest_mta_station    85217
dtype: int64

In [40]:
# Check stations where capacity is NA
station_data_merged[station_data_merged["capacity"].isna()]["station_id"].nunique()

122

In [41]:
# Drop stations where capacity is NA
station_data_merged = station_data_merged.dropna(subset=["capacity"]).copy()
station_data_merged = station_data_merged[station_data_merged["capacity"] > 0].copy()

In [42]:
# Check number of rows, columns after drop
station_data_merged.shape

(1650819, 15)

#### Dock availability

Calculate current dock availability and shift each station's time series two observations forward to measure availability about 30 minutes later. Only pairs separated by 25–35 minutes are retained.

In [43]:
# Compute available percentage per timestamp
station_data_merged["current_dock_pct"] = (
    station_data_merged["num_docks_available"] / station_data_merged["capacity"]
)

station_data_merged.head(5)

,station_id,num_bikes_available,num_docks_available,timestamp,snapshot_time,snapshot_hr,snapshot_weekday,is_weekend,citi_bike_station_name,citi_bike_lat,citi_bike_lon,capacity,region_id,nearest_mta_station,meters_to_nearest_mta_station,current_dock_pct
2010,00284700-9d22-42ce-8485-113fed9879c1,11,6,2026-07-30 10:58:57,2026-07-30 11:00:42,11,3,0,28 Ave & 44 St,40.764089,-73.910651,19.0,71,46 St,893.80959,0.315789
4529,00284700-9d22-42ce-8485-113fed9879c1,11,6,2026-07-30 11:29:19,2026-07-30 11:30:42,11,3,0,28 Ave & 44 St,40.764089,-73.910651,19.0,71,46 St,893.80959,0.315789
7006,00284700-9d22-42ce-8485-113fed9879c1,10,8,2026-07-30 11:58:40,2026-07-30 12:00:43,12,3,0,28 Ave & 44 St,40.764089,-73.910651,19.0,71,46 St,893.80959,0.421053
9077,00284700-9d22-42ce-8485-113fed9879c1,2,15,2026-07-30 12:27:50,2026-07-30 12:30:42,12,3,0,28 Ave & 44 St,40.764089,-73.910651,19.0,71,46 St,893.80959,0.789474
11468,00284700-9d22-42ce-8485-113fed9879c1,3,14,2026-07-30 12:58:10,2026-07-30 13:00:43,13,3,0,28 Ave & 44 St,40.764089,-73.910651,19.0,71,46 St,893.80959,0.736842

In [44]:
# Drop rows where current dock count exceeds station capacity
station_data_merged = station_data_merged[
    station_data_merged["num_docks_available"] <= station_data_merged["capacity"]
].copy()

station_data_merged.shape

(1650140, 16)

In [45]:
# Verify operation
(station_data_merged["num_docks_available"] > station_data_merged["capacity"]).sum()

0

In [46]:
# Check for duplicates before shifting
duplicate_station_time = station_data_merged.duplicated(
    subset=["station_id", "snapshot_time"]
).sum()

print(f"Duplicate station_id + snapshot_time rows: {duplicate_station_time}")

Duplicate station_id + snapshot_time rows: 0

In [47]:
# Shift future docks available within each station
station_data_merged["future_num_docks_available"] = (
    station_data_merged.groupby("station_id")["num_docks_available"].shift(-1)
)

station_data_merged.head(5)

,station_id,num_bikes_available,num_docks_available,timestamp,snapshot_time,snapshot_hr,snapshot_weekday,is_weekend,citi_bike_station_name,citi_bike_lat,citi_bike_lon,capacity,region_id,nearest_mta_station,meters_to_nearest_mta_station,current_dock_pct,future_num_docks_available
2010,00284700-9d22-42ce-8485-113fed9879c1,11,6,2026-07-30 10:58:57,2026-07-30 11:00:42,11,3,0,28 Ave & 44 St,40.764089,-73.910651,19.0,71,46 St,893.80959,0.315789,6.0
4529,00284700-9d22-42ce-8485-113fed9879c1,11,6,2026-07-30 11:29:19,2026-07-30 11:30:42,11,3,0,28 Ave & 44 St,40.764089,-73.910651,19.0,71,46 St,893.80959,0.315789,8.0
7006,00284700-9d22-42ce-8485-113fed9879c1,10,8,2026-07-30 11:58:40,2026-07-30 12:00:43,12,3,0,28 Ave & 44 St,40.764089,-73.910651,19.0,71,46 St,893.80959,0.421053,15.0
9077,00284700-9d22-42ce-8485-113fed9879c1,2,15,2026-07-30 12:27:50,2026-07-30 12:30:42,12,3,0,28 Ave & 44 St,40.764089,-73.910651,19.0,71,46 St,893.80959,0.789474,14.0
11468,00284700-9d22-42ce-8485-113fed9879c1,3,14,2026-07-30 12:58:10,2026-07-30 13:00:43,13,3,0,28 Ave & 44 St,40.764089,-73.910651,19.0,71,46 St,893.80959,0.736842,13.0

In [48]:
# Create future snapshot time
station_data_merged["future_snapshot_time"] = (
    station_data_merged.groupby("station_id")["snapshot_time"].shift(-1)
)

station_data_merged.head(5)

,station_id,num_bikes_available,num_docks_available,timestamp,snapshot_time,snapshot_hr,snapshot_weekday,is_weekend,citi_bike_station_name,citi_bike_lat,citi_bike_lon,capacity,region_id,nearest_mta_station,meters_to_nearest_mta_station,current_dock_pct,future_num_docks_available,future_snapshot_time
2010,00284700-9d22-42ce-8485-113fed9879c1,11,6,2026-07-30 10:58:57,2026-07-30 11:00:42,11,3,0,28 Ave & 44 St,40.764089,-73.910651,19.0,71,46 St,893.80959,0.315789,6.0,2026-07-30 11:30:42
4529,00284700-9d22-42ce-8485-113fed9879c1,11,6,2026-07-30 11:29:19,2026-07-30 11:30:42,11,3,0,28 Ave & 44 St,40.764089,-73.910651,19.0,71,46 St,893.80959,0.315789,8.0,2026-07-30 12:00:43
7006,00284700-9d22-42ce-8485-113fed9879c1,10,8,2026-07-30 11:58:40,2026-07-30 12:00:43,12,3,0,28 Ave & 44 St,40.764089,-73.910651,19.0,71,46 St,893.80959,0.421053,15.0,2026-07-30 12:30:42
9077,00284700-9d22-42ce-8485-113fed9879c1,2,15,2026-07-30 12:27:50,2026-07-30 12:30:42,12,3,0,28 Ave & 44 St,40.764089,-73.910651,19.0,71,46 St,893.80959,0.789474,14.0,2026-07-30 13:00:43
11468,00284700-9d22-42ce-8485-113fed9879c1,3,14,2026-07-30 12:58:10,2026-07-30 13:00:43,13,3,0,28 Ave & 44 St,40.764089,-73.910651,19.0,71,46 St,893.80959,0.736842,13.0,2026-07-30 13:30:42

In [49]:
# Future dock availability percentage
station_data_merged["future_dock_pct"] = (
    station_data_merged["future_num_docks_available"] / station_data_merged["capacity"]
)

In [50]:
# Check impossible future dock percentages
(station_data_merged["future_dock_pct"] > 1).sum()

0

In [51]:
# Drop rows where future dock count exceeds station capacity
station_data_merged = station_data_merged[
    station_data_merged["future_num_docks_available"] <= station_data_merged["capacity"]
].copy()

In [52]:
# Preview first five rows with new transformation
station_data_merged.head()

,station_id,num_bikes_available,num_docks_available,timestamp,snapshot_time,snapshot_hr,snapshot_weekday,is_weekend,citi_bike_station_name,citi_bike_lat,citi_bike_lon,capacity,region_id,nearest_mta_station,meters_to_nearest_mta_station,current_dock_pct,future_num_docks_available,future_snapshot_time,future_dock_pct
2010,00284700-9d22-42ce-8485-113fed9879c1,11,6,2026-07-30 10:58:57,2026-07-30 11:00:42,11,3,0,28 Ave & 44 St,40.764089,-73.910651,19.0,71,46 St,893.80959,0.315789,6.0,2026-07-30 11:30:42,0.315789
4529,00284700-9d22-42ce-8485-113fed9879c1,11,6,2026-07-30 11:29:19,2026-07-30 11:30:42,11,3,0,28 Ave & 44 St,40.764089,-73.910651,19.0,71,46 St,893.80959,0.315789,8.0,2026-07-30 12:00:43,0.421053
7006,00284700-9d22-42ce-8485-113fed9879c1,10,8,2026-07-30 11:58:40,2026-07-30 12:00:43,12,3,0,28 Ave & 44 St,40.764089,-73.910651,19.0,71,46 St,893.80959,0.421053,15.0,2026-07-30 12:30:42,0.789474
9077,00284700-9d22-42ce-8485-113fed9879c1,2,15,2026-07-30 12:27:50,2026-07-30 12:30:42,12,3,0,28 Ave & 44 St,40.764089,-73.910651,19.0,71,46 St,893.80959,0.789474,14.0,2026-07-30 13:00:43,0.736842
11468,00284700-9d22-42ce-8485-113fed9879c1,3,14,2026-07-30 12:58:10,2026-07-30 13:00:43,13,3,0,28 Ave & 44 St,40.764089,-73.910651,19.0,71,46 St,893.80959,0.736842,13.0,2026-07-30 13:30:42,0.684211

In [53]:
# Check whether shifted row is actually about 30 minutes later
station_data_merged["minutes_to_future"] = (
    station_data_merged["future_snapshot_time"] - station_data_merged["snapshot_time"]
).dt.total_seconds() / 60

station_data_merged["minutes_to_future"].value_counts().sort_index()

minutes_to_future
29.983333        290745
30.000000       1008939
30.016667        281577
59.983333             4
60.000000             9
                 ...
2970.000000           1
5910.000000           1
6750.016667           1
9719.983333           1
20190.000000          1
Name: count, Length: 62, dtype: int64

In [54]:
# Drop rows where minutes to future is less than 25 or greater than 55
station_data_merged = station_data_merged[
    (station_data_merged["minutes_to_future"] >= 25) &
    (station_data_merged["minutes_to_future"] <= 35)
].copy()

station_data_merged.shape

(1581261, 20)

In [55]:
# Drop rows with no future
station_data_merged = station_data_merged.dropna(
    subset=["future_num_docks_available", "future_snapshot_time", "future_dock_pct"]
).copy()

station_data_merged.shape

(1581261, 20)

#### Create target column

A positive case is a station that is currently above 10% dock availability but falls to 10% or less within the next 30 minutes. After filtering to stations that are currently above the low-dock threshold, about 4% of observations are positive cases.

In [56]:
# Create target
station_data_merged["lda"] = (
    station_data_merged["future_dock_pct"] <= 0.10
).astype(int)

station_data_merged["lda"].value_counts()

lda
0    1240089
1     341172
Name: count, dtype: int64

#### Check data types before export

Run a final check of data types and missing values before sending the cleaned dataset to exploratory analysis.

In [57]:
station_data_merged_types = pd.DataFrame()
station_data_merged_types["Data Type"] = station_data_merged.dtypes
station_data_merged_types["Count of Nulls"] = station_data_merged.isna().sum()
station_data_merged_types

                                    Data Type  Count of Nulls
station_id                             object               0
num_bikes_available                     int64               0
num_docks_available                     int64               0
timestamp                      datetime64[ns]               0
snapshot_time                  datetime64[ns]               0
snapshot_hr                             int32               0
snapshot_weekday                        int32               0
is_weekend                              int64               0
citi_bike_station_name                 object               0
citi_bike_lat                         float64               0
citi_bike_lon                         float64               0
capacity                              float64               0
region_id                              object               0
nearest_mta_station                    object               0
meters_to_nearest_mta_station         float64               0
current_dock_pct                      float64               0
future_num_docks_available            float64               0
future_snapshot_time           datetime64[ns]               0
future_dock_pct                       float64               0
minutes_to_future                     float64               0
lda                                     int32               0

#### Drop unneeded columns

Remove intermediate fields that are no longer needed for exploratory analysis or modeling.

In [58]:
station_data_merged = station_data_merged.drop(columns=[
    "timestamp",
    "nearest_mta_station",
    "region_id",
    "is_weekend"
]).copy()

station_data_merged.columns

Index(['station_id', 'num_bikes_available', 'num_docks_available',
       'snapshot_time', 'snapshot_hr', 'snapshot_weekday',
       'citi_bike_station_name', 'citi_bike_lat', 'citi_bike_lon', 'capacity',
       'meters_to_nearest_mta_station', 'current_dock_pct',
       'future_num_docks_available', 'future_snapshot_time', 'future_dock_pct',
       'minutes_to_future', 'lda'],
      dtype='object')

#### Export for exploratory analysis

Save the cleaned station-level dataset for use in the exploratory analysis notebook.

In [59]:
station_data_merged.to_parquet(
    CLEAN_DATA_DIR / "01_citi_bike_prediction_preprocessing.parquet",
    index=False
)